# site name
prefixName: sunwarm
siteName: 美食の小屋
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/avatar/sunwarm2001.jpg
#url: https://sunwarm.top
description: 越努力越进步越开心越自信


# 名字logo
logo:
  sakuraso: 美食
  no: の
  shironeko: 小屋

#建站时间
siteBuildingTime: 2020-11-06 00:00:00 # your site build time or founded date(2020-05-20 17:20:00)

#cdn图库
cdn: https://cdn.jsdelivr.net/gh/sunwarm2001/cdn


pjax: 1
# 1开启
mathjax: 0

notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  #在zh-cn.yml下配置  fa：Font Awesome下的图标路径
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    标签: {path: /tags, fa: fa-tags }, 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    #随想: {path: /categories/随想/, fa: fa-commenting-o },
    #转载: {path: /categories/转载/, fa: fa-book }
  } }
  #fa：Font Awesome下的图标路径
  #阅读和相册是在tags下的，所以在zh-cn.yml下配置
  #追加和歌单是在source目录下配置
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    阅读: {path: /tags/阅读, fa: fa-th-list faa-bounce }, 
    追剧: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    相册: {path: /tags/相册/, fa: fa-photo }
  } }
  #路径：在source目录下配置
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 12
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/1.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/2.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/3.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/4.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/6.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/8.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/10.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/11.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/15.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/20.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/28.jpg.webp
  - https://cdn.jsdelivr.net/gh/sunwarm2001/cdn/img/cover/90.jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



#social  url, img PC端配置
social:
  gitee: {url: https://gitee.com/sunwarm2001, img: /img/social/gitee.png}
  github: {url: https://github.com/sunwarm2001, img: /img/social/github.png}
  csdn: {url: https://blog.csdn.net/weixin_44653598, img: /img/social/csdn.png}
  zhihu: {url: https://www.zhihu.com/people/mu-yi-ue, img: /img/social/zhihu.png}
  #jianshu: {url: /https://www.jianshu.com/u/9b726a534140, img: /img/social/jianshu.png}
  # sina: {url: http://weibo.com/3829198906/info, img: /img/social/sina.png}
  bilibili: {url: https://space.bilibili.com/391135111, img: /img/social/bilibili.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=1412771417, img: /img/social/wangyiyun.png}
  #wechat: {url: /#, qrcode: /img/custom/cungudafa.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/sunwarm2001, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/3829198906/info, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2627039020&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  csdn: {url: https://blog.csdn.net/weixin_44653598, fa: fa-star, color: ff9900}

donate:
  #paypal: https://www.paypal.me/hojuncn
  #赏
  alipay: /img/custom/donate/1.jpg
  wechat: /img/custom/donate/2.jpg
  #微信好友
  wechatSQ: /img/custom/donate/3.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine 评论
valine: true
v_appId: dquiec0Mu5euKiDRrNaA8chH-gzGzoHsz
v_appKey: bwtQQPXTuxXeVnaPsO7S1e2R


# 是否开启文章字数统计
#不需要使用，直接设置值为false，或注释掉
word_count: true


# 是否开启访问量统计功能(不蒜子)
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次
